#!/bin/bash
# =============================================================================
# GENERATED by build-installer.sh from install.sh.in + ai-inventory-collector.zsh
# DO NOT EDIT THIS FILE; edit the sources and re-run ./build-installer.sh
# =============================================================================
# SPDX-FileCopyrightText: 2026 Robert Flanagan and macadmin-toolbox contributors
# SPDX-License-Identifier: MIT
#
# Name:        install.sh
# Purpose:     Self-contained installer for the AI Software Inventory
#              collector: writes the collector script and its LaunchDaemon,
#              then loads the daemon. --uninstall removes everything.
# Context:     Jamf policy (as root) or standalone: sudo ./install.sh [--uninstall]
# Parameters:  $4 = action: blank/install or --uninstall/uninstall
#              $5 = reverse-DNS label prefix, default io.github.ai-software-inventory
#              $6 = collection interval seconds, default 14400, minimum 600
#              $7 = absolute log path, default /var/log/ai-software-inventory.collector.log
# Tested on:   macOS 15.7.7 Sequoia
# Author:      Robert Flanagan (@r4828)
#
# $6 is recorded in ${STATE_DIR}/interval; the EA reader derives its staleness
# threshold (2x interval) from that file, falling back to 28800 s if absent.

set -eu
umask 022

REVERSE_DOMAIN="${5:-io.github.ai-software-inventory}"
# The label lands in a filesystem path and in plist XML; keep it reverse-DNS.
case "${REVERSE_DOMAIN}" in
    *[!A-Za-z0-9.-]*|*..*|.*|*.)
        echo "install.sh: parameter 5 (REVERSE_DOMAIN) must be a reverse-DNS label (letters, digits, '.', '-'), got '${REVERSE_DOMAIN}'" >&2
        exit 1
        ;;
esac
PROJECT="ai-software-inventory"
START_INTERVAL="${6:-14400}"

LABEL="${REVERSE_DOMAIN}.collector"
INSTALL_DIR="/usr/local/${PROJECT}"
COLLECTOR_NAME="ai-inventory-collector.zsh"
COLLECTOR_DEST="${INSTALL_DIR}/${COLLECTOR_NAME}"
PLIST_DEST="/Library/LaunchDaemons/${LABEL}.plist"
STATE_DIR="/var/db/${PROJECT}"
LOG_FILE="${7:-/var/log/${PROJECT}.collector.log}"

# Fail visibly on a bad cadence.
case "${START_INTERVAL}" in
    ''|*[!0-9]*)
        echo "install.sh: parameter 6 (START_INTERVAL) must be an integer number of seconds, got '${START_INTERVAL}'" >&2
        exit 1
        ;;
esac
if [ "${START_INTERVAL}" -lt 600 ]; then
    echo "install.sh: parameter 6 (START_INTERVAL) must be >= 600 seconds, got ${START_INTERVAL}" >&2
    exit 1
fi

# LaunchDaemon log paths must be absolute.
case "${LOG_FILE}" in
    /*) : ;;
    *)
        echo "install.sh: parameter 7 (LOG_FILE) must be an absolute path, got '${LOG_FILE}'" >&2
        exit 1
        ;;
esac

log() {
    echo "[install.sh] $*"
}

do_uninstall() {
    log "Uninstalling ${LABEL} ..."
    if [ ! -f "${PLIST_DEST}" ]; then
        log "WARNING: ${PLIST_DEST} not found. If the install used a custom parameter 5 (label prefix), rerun --uninstall with that same value; continuing cleanup of the paths above."
    fi
    launchctl bootout "system/${LABEL}" 2>/dev/null || true
    rm -f "${PLIST_DEST}"
    rm -rf "${INSTALL_DIR}"
    rm -rf "${STATE_DIR}"
    log "Uninstalled. ${LOG_FILE} left in place (rotate/remove manually if desired)."
}

# Direct runs use $1; Jamf policy scripts start custom parameters at $4.
if [ "${1:-}" = "--uninstall" ] || [ "${4:-}" = "--uninstall" ] || [ "${4:-}" = "uninstall" ]; then
    if [ "$(id -u)" -ne 0 ]; then
        echo "install.sh --uninstall must run as root." >&2
        exit 1
    fi
    do_uninstall
    exit 0
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "install.sh must run as root (e.g. via a Jamf policy running as root, or sudo)." >&2
    exit 1
fi

log "Installing collector -> ${COLLECTOR_DEST}"
mkdir -p "${INSTALL_DIR}"
chown root:wheel "${INSTALL_DIR}"
chmod 0755 "${INSTALL_DIR}"
cat > "${COLLECTOR_DEST}" <<'__AI_COLLECTOR_EOF__'
#!/bin/zsh --no-rcs
# SPDX-FileCopyrightText: 2026 Robert Flanagan and macadmin-toolbox contributors
# SPDX-License-Identifier: MIT
#
# Name:        ai-inventory-collector.zsh
# Purpose:     Background collector for the Jamf AI Software Inventory EA.
#              Scans local apps/tools/configs and writes the EA inner value
#              to /var/db/ai-software-inventory/result.txt. Do not wrap output
#              in <result>; ai-software-inventory-ea.zsh does that during recon.
# Context:     LaunchDaemon (installed by install.sh); runs as root on a timer.
# Parameters:  none
# Tested on:   macOS 15.7.7 Sequoia
# Author:      Robert Flanagan (@r4828)
#
# No network calls. Team-ID matches are verified with offline codesign.

export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

# Use fixed paths; launchd's PATH is not an API.
GREP=/usr/bin/grep
SED=/usr/bin/sed
AWK=/usr/bin/awk
FIND=/usr/bin/find
SORT=/usr/bin/sort
TR=/usr/bin/tr
HEAD=/usr/bin/head
MKTEMP=/usr/bin/mktemp
BASENAME=/usr/bin/basename
DIRNAME=/usr/bin/dirname
CUT=/usr/bin/cut
PLUTIL=/usr/bin/plutil
CODESIGN=/usr/bin/codesign
MKDIR=/bin/mkdir
MV=/bin/mv
CHOWN=/usr/sbin/chown
CHMOD=/bin/chmod

# Do not use err_exit: most scan paths are optional and expected to miss.

umask 077   # any temp we create is root-only until explicitly chmod'd below

# Must match ai-software-inventory-ea.zsh.
: ${AI_INV_STATE_DIR:=/var/db/ai-software-inventory}
STATE_DIR="$AI_INV_STATE_DIR"
STATE_FILE="$STATE_DIR/result.txt"

# Accumulate TAB-separated findings: CATEGORY, Friendly, id, location.
# Fallback temp path is root-only, never world-writable /tmp.
WORK="$("$MKTEMP" -t ai_sw_inv.XXXXXX 2>/dev/null)" || WORK="/var/root/.ai_sw_inv.$$"
WORK_OK=1
: > "$WORK" 2>/dev/null || WORK_OK=0
trap 'rm -f "$WORK" "$STATE_FILE.tmp.$$" 2>/dev/null' EXIT   # also reaps an orphaned state tmpfile if killed mid-rename

# Escape user-controlled names before the EA reader wraps them in <result>.
xesc() {
    local s=$1
    s=${s//[[:cntrl:]]/ }
    s=${s//&/&amp;}
    s=${s//</&lt;}
    s=${s//>/&gt;}
    print -r -- "$s"
}

emit() { # emit CATEGORY  Friendly  id  location
    printf '%s\t%s\t%s\t%s\n' "$1" "$(xesc "$2")" "$(xesc "$3")" "$(xesc "$4")" >> "$WORK"
}

# Real user homes only; (N/) means directories, null if none.
user_homes=()
for h in /Users/*(N/); do
    case "$h" in
        /Users/Shared|/Users/.localized|/Users/Guest) continue ;;
    esac
    user_homes+=("$h")
done

lc() { printf '%s' "$1" | "$TR" '[:upper:]' '[:lower:]'; }

# Conservative AI-token heuristic; avoid bare ai/gpt/amp/zed false positives.
AI_HEURISTIC='chatgpt|openai|anthropic|claude|copilot|codeium|windsurf|cursor|gemini|ollama|llama|mistral|perplexity|tabnine|gpt4all|lm.?studio|deepseek|hugging.?face|langchain|comfyui|diffusionbee|stable.?diffusion|whisper|open.?interpreter|localai|jan\.ai|msty|anythingllm|generative.?ai|\bllm\b|genai|\bgpt-?[0-9]|openhands|gptme|ra-?aid|gpt-?engineer|mentat|codebuff|plandex|codegeex|auggie|qodo'

is_ai_heuristic() { printf '%s' "$1" | "$GREP" -Eiq "$AI_HEURISTIC"; }

# Curated AI-native Developer ID teams only. Diversified vendors are handled by
# bundle ID/name because they sign non-AI apps too.
teamid_known() {
    case "$1" in
        Q6L2SF6YDW) echo "Anthropic";;
        2DC432GLL2) echo "OpenAI";;
        D65G88RHWN) echo "Element Labs (LM Studio)";;
        3MU9H2V9Y9) echo "Infra Technologies (Ollama)";;
        7S8W4W365S) echo "Perplexity";;
        83GA966S9H) echo "PLAUD";;
        YJ5GSB3AMW) echo "Chatbox";;
        GJE9R5VE87) echo "ChatWise";;
        TPKP4XK352) echo "Pinokio";;
        6HP3U6Z7P6) echo "Draw Things";;
        QZ7DHHLN25) echo "Granola";;
        6AWUP5FE76) echo "Otter.ai";;
        U5R26XM5Z2) echo "Krisp";;
        DM5Z66639F) echo "Fireflies.ai";;
        89PS65RKC6) echo "Cluely";;
        6D5N473QP3) echo "BoltAI";;
        TP8BYQ64C4) echo "Witsy";;
        T7FPYN38JJ) echo "Tabnine";;
        83Z2LHX6XW) echo "Exafunction (Windsurf/Codeium/Devin)";;
        *) echo "";;
    esac
}

app_teamid() { # print the app's code-signing Team Identifier, or empty
    "$CODESIGN" -dv --verbose=4 "$1" 2>&1 | "$AWK" -F= '/^TeamIdentifier=/{print $2; exit}'
}

# Offline signature check for Team-ID matches. Do not replace this with spctl.
verify_signature() { "$CODESIGN" --verify "$1" >/dev/null 2>&1; }

# SECTION A: AI desktop applications.
app_known() {
    case "$1" in
        *claude-code-url-handler*)                 echo "Claude Code URL Handler (Anthropic)";;
        *com.anthropic.claudefordesktop*|*claude*) echo "Claude (Anthropic)";;
        *com.openai.atlas*)                        echo "ChatGPT Atlas (AI browser)";;
        *com.openai.chat*|*chatgpt*)               echo "ChatGPT (OpenAI)";;
        *com.openai.codex*|*"openai codex"*)       echo "OpenAI Codex";;
        *dev.kiro*|"kiro "*)                       echo "Kiro (Amazon, agentic IDE)";;
        "cursor "*|*com.todesktop.230313mzl4w4u92*) echo "Cursor";;
        *com.google.antigravity*|"antigravity "*)  echo "Google Antigravity (AI code editor)";;
        *com.exafunction.windsurf*|*windsurf*)     echo "Windsurf";;
        *ollamac*)                                 echo "Ollamac (AI chat client)";;
        *com.electron.ollama*|*ollama*)            echo "Ollama (local LLM runtime)";;
        *lmstudio*|*lm-studio*|*"lm studio"*)      echo "LM Studio (local LLM runtime)";;
        *ai.perplexity.comet*)                     echo "Perplexity Comet (AI browser)";;
        *ai.perplexity*|*perplexity*)              echo "Perplexity";;
        *gpt4all*)                                 echo "GPT4All (local LLM runtime)";;
        *anythingllm*)                             echo "AnythingLLM";;
        *ai.jan*|*"jan.ai"*)                       echo "Jan (local LLM runtime)";;
        "msty "*|*app.msty*)                       echo "Msty (local LLM runtime)";;
        *computer.pinokio*|*pinokio*)              echo "Pinokio (local LLM runtime)";;
        *backyard*|*dev.faraday*)                  echo "Backyard AI (local LLM runtime)";;
        *com.invoke*|*invokeai*)                   echo "InvokeAI (image gen)";;
        *com.liuliu.draw-things*|*"draw things"*|*drawthings*) echo "Draw Things (image gen)";;
        *diffusionbee*)                            echo "DiffusionBee (image gen)";;
        *comfyui*)                                 echo "ComfyUI (image gen)";;
        *com.descript*|*descript*)                 echo "Descript (AI audio/video)";;
        *superwhisper*|*macwhisper*)               echo "Whisper transcription app";;
        "aiko "*|*com.sindresorhus.aiko*)          echo "Aiko (Whisper transcription)";;
        *granola*)                                 echo "Granola (AI notetaker)";;
        "otter "*|*com.aisense.otter*)             echo "Otter (AI notetaker)";;
        *krisp*)                                   echo "Krisp (AI notetaker)";;
        *fireflies*)                               echo "Fireflies (AI notetaker)";;
        "fathom "*|*video.fathom*)                 echo "Fathom (AI notetaker)";;
        *tldv*|*"tl;dv"*)                          echo "tl;dv (AI notetaker)";;
        *cluely*)                                  echo "Cluely (AI assistant)";;
        *xyz.chatboxapp*|"chatbox "*)              echo "Chatbox (AI chat client)";;
        *app.chatwise*|"chatwise "*)               echo "ChatWise (AI chat client)";;
        *com.boltai*|*boltai*)                     echo "BoltAI (AI chat client)";;
        *com.nabocorp.witsy*|*witsy*)              echo "Witsy (AI chat client)";;
        *typingmind*)                              echo "TypingMind (AI chat client)";;
        *jordibruin.macgpt*|*macgpt*)              echo "MacGPT (AI chat client)";;
        *cherry*studio*)                           echo "Cherry Studio (AI chat client)";;
        "enchanted "*)                             echo "Enchanted (LLM client)";;
        *dev.warp.warp*)                           echo "Warp (AI terminal)";;
        *dev.zed.zed*)                             echo "Zed (AI code editor)";;
        *company.thebrowser.dia*)                  echo "Dia (AI browser)";;
        *com.trae*|*marscode*)                     echo "Trae (AI code editor)";;
        *trypear*|*pearai*)                        echo "PearAI (AI code editor)";;
        *voideditor*)                              echo "Void (AI code editor)";;
        *amazonq*|*"amazon q"*)                    echo "Amazon Q";;
        *com.microsoft.copilot*)                   echo "Microsoft Copilot";;
        *) echo "";;
    esac
}

scan_apps() {
    local -a roots
    local h app base bid blob friendly team vendor
    roots=(/Applications /Applications/Utilities /System/Applications/Utilities)
    for h in $user_homes; do roots+=("$h/Applications"); done
    # Covers /Applications/Vendor/Thing.app without deep recursion.
    "$FIND" $roots -maxdepth 3 -name '*.app' -type d -prune 2>/dev/null | while IFS= read -r app; do
        base="$("$BASENAME" "$app" .app)"
        bid="$("$PLUTIL" -extract CFBundleIdentifier raw -o - "$app/Contents/Info.plist" 2>/dev/null)"
        blob="$(lc "$base $bid")"

        friendly="$(app_known "$blob")"
        if [[ -n "$friendly" ]]; then
            emit "APP" "$friendly" "${bid:-$base}" "$app"
            continue
        fi

        # Team-ID fallback only runs after name/bundle matching.
        team="$(app_teamid "$app")"
        vendor="$(teamid_known "$team")"
        if [[ -n "$vendor" ]]; then
            if verify_signature "$app"; then
                emit "APP" "$base (Developer ID: $vendor)" "${bid:-$base} [Team $team verified]" "$app"
            else
                # Keep failed Team-ID matches visible for review.
                emit "HEURISTIC" "$base (Developer ID: $vendor, signature FAILED verify)" "${bid:-$base} [Team $team UNVERIFIED]" "$app"
            fi
        elif [[ -n "$bid" ]] && printf '%s' "$bid" | "$GREP" -Eiq '^ai\.'; then
            emit "HEURISTIC" "$base (reverse-domain .ai vendor)" "$bid" "$app"
        elif is_ai_heuristic "$blob"; then
            emit "HEURISTIC" "$base (AI keyword)" "${bid:-$base}" "$app"
        fi
    done
}

# SECTION B: AI command-line tools and coding agents.
# Generic binary names are detected by config/package evidence, not bare name.
cli_known() {
    case "$1" in
        claude)                 echo "Claude Code (Anthropic)";;
        codex)                  echo "OpenAI Codex";;
        gemini)                 echo "Gemini CLI (Google)";;
        cursor-agent)           echo "Cursor Agent";;
        aider)                  echo "Aider";;
        ollama)                 echo "Ollama (local LLM runtime)";;
        llm)                    echo "llm CLI (Datasette)";;
        sgpt|shell-gpt)         echo "Shell GPT";;
        mods)                   echo "mods (Charm)";;
        aichat)                 echo "aichat";;
        tgpt)                   echo "tgpt";;
        crush)                  echo "Crush (Charm)";;
        opencode)               echo "OpenCode";;
        kiro|kiro-cli)          echo "Kiro CLI";;
        cody)                   echo "Sourcegraph Cody";;
        chatgpt)                echo "ChatGPT CLI";;
        interpreter|open-interpreter) echo "Open Interpreter";;
        llamafile|llama-cli|llama-server) echo "llama.cpp";;
        amp)                    echo "Amp (Sourcegraph)";;
        openhands)              echo "OpenHands";;
        cline)                  echo "Cline";;
        auggie)                 echo "Auggie (Augment)";;
        qodo)                   echo "Qodo Command";;
        codebuff|freebuff)      echo "Codebuff";;
        ra-aid)                 echo "RA.Aid";;
        fabric)                 echo "Fabric";;   # not in the PATH-scan list; Fabric is detected via ~/.config/fabric below
        gptme)                  echo "gptme";;
        gpte|gpt-engineer)      echo "gpt-engineer";;
        plandex|pdx)            echo "Plandex";;
        butterfish)             echo "Butterfish";;
        mycoder)                echo "MyCoder";;
        mentat)                 echo "Mentat";;
        qchat|qterm)            echo "Amazon Q";;
        *) echo "";;
    esac
}

scan_cli() {
    # Binaries in system and per-user bin locations.
    local -a bindirs simple_cli_configs npmroots aiderhits
    local h d name entry suffix friendly r pkg pdir v vn
    bindirs=(/usr/local/bin /opt/homebrew/bin /opt/local/bin /usr/bin)
    for h in $user_homes; do
        bindirs+=("$h/.local/bin" "$h/bin" "$h/.npm-global/bin" "$h/.cargo/bin" "$h/.deno/bin" "$h/.bun/bin" \
                  "$h/Library/pnpm" "$h/.volta/bin" "$h/.asdf/shims" "$h/.claude/local")
    done
    for d in $bindirs; do
        [[ -d "$d" ]] || continue
        # No bare "copilot" or "goose" here: AWS Copilot (ECS) and pressly/goose
        # (database migrations) install binaries with those exact names. GitHub
        # Copilot CLI is caught by ~/.config/github-copilot and the
        # @github/copilot npm package; Block's Goose by ~/.config/goose.
        for name in claude codex gemini cursor-agent aider ollama llm sgpt shell-gpt \
                    mods aichat tgpt crush opencode kiro kiro-cli cody \
                    chatgpt interpreter open-interpreter llamafile llama-cli llama-server \
                    amp openhands cline auggie qodo codebuff freebuff ra-aid gptme \
                    gpte gpt-engineer plandex pdx butterfish mycoder mentat qchat qterm; do
            if [[ -e "$d/$name" || -L "$d/$name" ]]; then
                friendly="$(cli_known "$name")"
                [[ -n "$friendly" ]] && emit "CLI" "$friendly" "$name" "$d/$name"
            fi
        done
    done

    # Config/state dirs catch shims and tools with generic binary names.
    simple_cli_configs=(
        ".codex|OpenAI Codex (config present)"
        ".gemini|Gemini CLI (config present)"
        ".config/github-copilot|GitHub Copilot CLI (config present)"
        ".ollama|Ollama (config present)"
        ".continue|Continue CLI (config present)"
        ".openhands|OpenHands (config present)"
        ".augment|Auggie/Augment (config present)"
        ".qodo|Qodo (config present)"
        ".cline|Cline (config present)"
        ".forge|ForgeCode (config present)"
        ".factory|Factory Droid (config present)"
        ".grok|Grok CLI (config present)"
        ".mycoder|MyCoder (config present)"
        ".config/amp|Amp (config present)"
        ".config/goose|Goose (Block) (config present)"
        ".config/fabric|Fabric (config present)"
    )
    for h in $user_homes; do
        { [[ -e "$h/.claude" || -e "$h/.claude.json" ]]; } && emit "CLI" "Claude Code (config present)" "~/.claude" "$h/.claude"
        aiderhits=($h/.aider*(N))
        { [[ -d "$h/.aider" ]] || (( ${#aiderhits} )); } && emit "CLI" "Aider (config present)" "~/.aider" "$h/.aider*"
        { [[ -d "$h/.aws/amazonq" || -d "$h/.aws/q" ]]; } && emit "CLI" "Amazon Q Developer CLI (config present)" "~/.aws/amazonq" "$h/.aws/amazonq"
        for entry in $simple_cli_configs; do
            suffix="${entry%%|*}"
            friendly="${entry#*|}"
            [[ -d "$h/$suffix" ]] && emit "CLI" "$friendly" "~/$suffix" "$h/$suffix"
        done
    done

    # npm globals across system and per-user prefixes.
    npmroots=(/opt/homebrew/lib/node_modules /usr/local/lib/node_modules)
    for h in $user_homes; do
        npmroots+=(
            $h/.npm-global/lib/node_modules(N)
            $h/.nvm/versions/node/*/lib/node_modules(N)
            $h/n/lib/node_modules(N)
            $h/.config/yarn/global/node_modules(N)
        )
    done
    for r in $npmroots; do
        [[ -d "$r" ]] || continue
        for pkg in "@anthropic-ai/claude-code" "@openai/codex" "@google/gemini-cli" \
                   "@github/copilot" "opencode-ai" "@sourcegraph/cody" "@sourcegraph/amp" \
                   "@qwen-code/qwen-code" "@continuedev/cli" "@augmentcode/auggie" \
                   "@qodo/command" "codebuff" "@antinomyhq/forge" "cline" "mycoder" \
                   "@vibe-kit/grok-cli" "@shareai-lab/kode"; do
            [[ -d "$r/$pkg" ]] && emit "CLI" "npm: $pkg" "$pkg" "$r/$pkg"
        done
    done

    # pipx-managed AI CLIs.
    for h in $user_homes; do
        for pdir in "$h/.local/pipx/venvs" "$h/.local/share/pipx/venvs"; do
            [[ -d "$pdir" ]] || continue
            for v in $pdir/*(N); do
                [[ -d "$v" ]] || continue
                vn="$("$BASENAME" "$v")"
                is_ai_heuristic "$vn" && emit "CLI" "pipx: $vn" "$vn" "$v"
            done
        done
        # uv-managed tools.
        for v in "$h/.local/share/uv/tools"/*(N); do
            [[ -d "$v" ]] || continue
            vn="$("$BASENAME" "$v")"
            is_ai_heuristic "$vn" && emit "CLI" "uv: $vn" "$vn" "$v"
        done
    done
}

# SECTION C: Editor AI extensions/plugins.
ext_is_ai() {
    local lc_name
    lc_name="$(lc "$1")"
    case "$lc_name" in
        github.copilot*|continue.continue*|codeium.*|tabnine.*|sourcegraph.cody*|\
        sourcegraph.amp*|saoudrizwan.claude-dev*|rooveterinaryinc.roo-cline*|kilocode.*|\
        supermaven.*|google.geminicodeassist*|\
        amazonwebservices.amazon-q*|anthropic.*|\
        openai.*|blackboxapp.*|codegpt.*|danielsanmedium.dscodegpt*|\
        visualstudioexptteam.vscodeintellicode*|mintlify.*|bito.*|\
        sourcery.sourcery*|codium.codium*|augment.*|pythagora-io.*|\
        aminer.codegeex*|rjmacarthy.twinny*|tabbyml.*|doublebot.doublebot*|\
        codestoryai.*|meshintelligenttechnologiesinc.pieces*|alibaba-cloud.tongyi-lingma*|\
        marscode.*|baiducomate.*|smallcloud.codify*|zencoderai.*|sweepai.*|bloop.*|\
        codiga.*|mistralai.mistral-code*|ms-windows-ai-studio.*|venthe.fauxpilot*|\
        sitoi.ai-commit*|codemateai.*|askcodi.*)
            return 0;;
    esac
    is_ai_heuristic "$lc_name" && return 0
    return 1
}

scan_ide_ext() {
    local h extroot editor e en pubname jb p
    for h in $user_homes; do
        for extroot in "$h/.vscode/extensions" "$h/.vscode-insiders/extensions" \
                       "$h/.vscode-oss/extensions" "$h/.vscodium/extensions" \
                       "$h/.cursor/extensions" "$h/.windsurf/extensions" \
                       "$h/.antigravity/extensions"; do
            [[ -d "$extroot" ]] || continue
            editor="$("$BASENAME" "$("$DIRNAME" "$extroot")")"   # e.g. ".cursor"
            for e in $extroot/*(N); do
                [[ -d "$e" ]] || continue
                en="$("$BASENAME" "$e")"                       # publisher.name-version
                pubname="$(printf '%s' "$en" | "$SED" -E 's/-[0-9]+\.[0-9]+\.[0-9]+.*$//')"
                if ext_is_ai "$pubname"; then
                    emit "IDE-EXT" "$pubname" "$editor" "$e"
                fi
            done
        done
        # JetBrains plugin folders.
        jb="$h/Library/Application Support/JetBrains"
        [[ -d "$jb" ]] || continue
        "$FIND" "$jb" -maxdepth 3 -type d \( -iname '*copilot*' -o -iname '*codeium*' \
             -o -iname '*cody*' -o -iname '*ai-assistant*' -o -iname '*tabnine*' \
             -o -iname '*codegeex*' -o -iname '*codegpt*' -o -iname '*continue*' \
             -o -iname '*refact*' -o -iname '*amazon*q*' -o -iname '*marscode*' \
             -o -iname '*lingma*' -o -iname '*comate*' -o -iname '*zencoder*' \
             -o -iname '*supermaven*' -o -iname '*bito*' \) 2>/dev/null | while IFS= read -r p; do
            emit "IDE-EXT" "$("$BASENAME" "$p")" "JetBrains" "$p"
        done
    done
}

# SECTION D: Chromium-family browser AI extensions.
chrome_ext_known() {
    case "$1" in
        difoiogjjojoaoomphldepapgpbgkhkb) echo "Sider";;
        ofpnmcalabcbjgholdjcjblkibolbppb) echo "Monica";;
        camppjleccjaphfdbohjdohecfnoikec) echo "Merlin";;
        mhnlakgilnojmhinhkckjpncpbhabphi) echo "MaxAI";;
        eanggfilgoajaocelnaflolkadkeghjp) echo "Harpa AI";;
        ddlbpiadoechcolndfeaonajmngmhblj) echo "Compose AI";;
        cmknchgdgbkhmfdkageknhpgfeenekch|hacfaophiklaeolhnmckojjjjbnappen) echo "ChatGPT for Google";;
        hlgbcneanomplepojfcnclggenpcoldo) echo "Perplexity Companion";;
        cmnlolelipjlhfkhpohphpedmkfbobjc) echo "Glarity";;
        lpfemeioodjbpieminkklglpmhlngfcn) echo "WebChatGPT";;
        befflofjcniongenjmbkgkoljhgliihe) echo "TinaMind";;
        paodpkkacimmkacaecjmhdncjgjepcai) echo "Wiseone";;
        inapcehmmoncbiejodbkokcijkpdkgja|nelhhkchoapcbpcgpmmiahfkcdhgecaf|fmddplceibafdomknoaimellkpgffchl) echo "Engage AI";;
        kbfnbcaeplbcioakkpcpgfkobkghlhen) echo "Grammarly";;
        bpiohchncadidhohcajcnoelomephkdd) echo "Jasper Everywhere";;
        cakobppopkpmmglabcdcklncbckjpkcl) echo "Voila";;
        pdnenlnelpdomajfejgapbdpmjkfpjkp) echo "ChatGPT Writer";;
        ojnbohmppadfgpejeebfnmnknjdlckgj) echo "AIPRM";;
        amhmeenmapldpjdedekalnfifgnpfnkc) echo "Superpower ChatGPT";;
        fcoeoabgfenejglbffodgkkbkcdhcgfn) echo "Claude for Chrome";;
        *) echo "";;
    esac
}

# Bounded manifest-name scan for unknown extensions.
scan_browser_ext() {
    local h broot browser mf extid known nm extdir msg
    for h in $user_homes; do
        for broot in \
            "$h/Library/Application Support/Google/Chrome" \
            "$h/Library/Application Support/Google/Chrome Beta" \
            "$h/Library/Application Support/Microsoft Edge" \
            "$h/Library/Application Support/BraveSoftware/Brave-Browser" \
            "$h/Library/Application Support/Chromium" \
            "$h/Library/Application Support/Vivaldi" \
            "$h/Library/Application Support/Comet" \
            "$h/Library/Application Support/Arc" \
            "$h/Library/Application Support/Dia" \
            "$h/Library/Application Support/company.thebrowser.dia"; do
            [[ -d "$broot" ]] || continue
            browser="$("$BASENAME" "$broot")"
            # Depth 6 catches Arc/Dia's extra "User Data" level.
            "$FIND" "$broot" -maxdepth 6 -path '*/Extensions/*/manifest.json' 2>/dev/null | "$HEAD" -n 500 | while IFS= read -r mf; do
                # Accept only Extensions/<id>/<version>/manifest.json.
                [[ "$("$BASENAME" "$("$DIRNAME" "$("$DIRNAME" "$("$DIRNAME" "$mf")")")")" == "Extensions" ]] || continue
                extid="$("$BASENAME" "$("$DIRNAME" "$("$DIRNAME" "$mf")")")"
                known="$(chrome_ext_known "$extid")"
                if [[ -n "$known" ]]; then
                    # Store ID is stable; location records the browser.
                    emit "BROWSER-EXT" "$known" "$extid" "$browser"
                    continue
                fi
                nm="$("$GREP" -Eo '"name"[[:space:]]*:[[:space:]]*"[^"]*"' "$mf" 2>/dev/null | "$HEAD" -1 | "$SED" -E 's/.*:[[:space:]]*"//; s/"$//')"
                case "$nm" in
                    __MSG_*)
                        extdir="$("$DIRNAME" "$("$DIRNAME" "$mf")")"
                        msg="$("$FIND" "$extdir" -maxdepth 3 -path '*_locales/en*/messages.json' 2>/dev/null | "$HEAD" -1)"
                        [[ -n "$msg" ]] && nm="$("$GREP" -Eo '"message"[[:space:]]*:[[:space:]]*"[^"]*"' "$msg" 2>/dev/null | "$HEAD" -1 | "$SED" -E 's/.*:[[:space:]]*"//; s/"$//')"
                        ;;
                esac
                [[ -z "$nm" ]] && continue
                if is_ai_heuristic "$nm"; then
                    emit "BROWSER-EXT" "$nm" "$browser" "$mf"
                fi
            done
        done
    done
}

# SECTION E: MCP configuration on stable user and system paths.
scan_mcp() {
    local h cdc vsc f
    local -a cdext plugmcp kirows
    for h in $user_homes; do
        # Claude Desktop config.
        cdc="$h/Library/Application Support/Claude/claude_desktop_config.json"
        [[ -f "$cdc" ]] && "$GREP" -q 'mcpServers' "$cdc" 2>/dev/null && emit "MCP" "Claude Desktop MCP" "configured" "$cdc"
        # Desktop Extensions can bundle MCP servers outside claude_desktop_config.json.
        cdext=("$h/Library/Application Support/Claude/Claude Extensions"/*(N/))
        (( ${#cdext} )) && emit "MCP" "Claude Desktop Extensions MCP" "${#cdext} extension bundle(s)" "$h/Library/Application Support/Claude/Claude Extensions"
        # Claude Code user scope.
        [[ -f "$h/.claude.json" ]] && "$GREP" -q 'mcpServers' "$h/.claude.json" 2>/dev/null && emit "MCP" "Claude Code MCP" "configured" "$h/.claude.json"
        # Claude Code plugin MCP manifests.
        plugmcp=("$h"/.claude/plugins/**/.mcp.json(N))
        (( ${#plugmcp} )) && emit "MCP" "Claude Code plugin MCP" "${#plugmcp} plugin manifest(s)" "$h/.claude/plugins"
        # Cursor user scope.
        [[ -f "$h/.cursor/mcp.json" ]] && emit "MCP" "Cursor MCP" "configured" "$h/.cursor/mcp.json"
        # OpenAI Codex CLI.
        [[ -f "$h/.codex/config.toml" ]] && "$GREP" -qi 'mcp' "$h/.codex/config.toml" 2>/dev/null && emit "MCP" "Codex MCP" "configured" "$h/.codex/config.toml"
        # VS Code family user-profile MCP config.
        for vsc in "$h/Library/Application Support/Code" \
                   "$h/Library/Application Support/Code - Insiders" \
                   "$h/Library/Application Support/VSCodium"; do
            for f in "$vsc/User/mcp.json" "$vsc/User/profiles"/*/mcp.json(N); do
                [[ -f "$f" ]] && "$GREP" -q '"servers"' "$f" 2>/dev/null && emit "MCP" "VS Code MCP" "configured" "$f"
            done
        done
        # Gemini CLI.
        [[ -f "$h/.gemini/settings.json" ]] && "$GREP" -q 'mcpServers' "$h/.gemini/settings.json" 2>/dev/null && emit "MCP" "Gemini CLI MCP" "configured" "$h/.gemini/settings.json"
        # Kiro user and workspace config.
        [[ -f "$h/.kiro/settings/mcp.json" ]] && emit "MCP" "Kiro MCP" "configured" "$h/.kiro/settings/mcp.json"
        # Windsurf.
        [[ -f "$h/.codeium/windsurf/mcp_config.json" ]] && emit "MCP" "Windsurf MCP" "configured" "$h/.codeium/windsurf/mcp_config.json"
        # Zed.
        [[ -f "$h/.config/zed/settings.json" ]] && "$GREP" -q 'context_servers' "$h/.config/zed/settings.json" 2>/dev/null && emit "MCP" "Zed MCP" "configured" "$h/.config/zed/settings.json"
        # LM Studio.
        [[ -f "$h/.lmstudio/mcp.json" ]] && "$GREP" -q 'mcpServers' "$h/.lmstudio/mcp.json" 2>/dev/null && emit "MCP" "LM Studio MCP" "configured" "$h/.lmstudio/mcp.json"
        # Goose.
        [[ -f "$h/.config/goose/config.yaml" ]] && "$GREP" -q 'extensions' "$h/.config/goose/config.yaml" 2>/dev/null && emit "MCP" "Goose MCP" "configured" "$h/.config/goose/config.yaml"
    done
    # Claude Code fleet-managed MCP path.
    [[ -f "/Library/Application Support/ClaudeCode/managed-mcp.json" ]] && emit "MCP" "Claude Code managed MCP (fleet policy)" "configured" "/Library/Application Support/ClaudeCode/managed-mcp.json"
}

# Each scan section is isolated so one failure does not hide the rest.
if (( WORK_OK )); then
    scan_apps        2>/dev/null
    scan_cli         2>/dev/null
    scan_ide_ext     2>/dev/null
    scan_browser_ext 2>/dev/null
    scan_mcp         2>/dev/null
fi

# Assemble the cached EA inner value.
if (( ! WORK_OK )); then
    # Preserve the previous state on scanner infrastructure failure.
    print -u2 "ai-inventory-collector: scratch file unavailable; leaving previous state file untouched"
    exit 1
fi
if [[ ! -s "$WORK" ]]; then
    body="None"
else
    sorted="$("$SORT" -u "$WORK")"

    # Collapse multiple evidence paths into one row per category/tool.
    sorted="$(printf '%s\n' "$sorted" | "$AWK" -F'\t' '
        BEGIN {
            OFS = "\t"
            alias["anthropic ai claude code"] = "claude code"
            alias["google gemini cli"]        = "gemini cli"
            alias["github copilot"]           = "github copilot cli"
            alias["opencode ai"]              = "opencode"
            alias["sourcegraph amp"]          = "amp"
            alias["continuedev cli"]          = "continue cli"
            alias["augmentcode auggie"]       = "auggie"
            alias["auggie augment"]           = "auggie"
            alias["antinomyhq forge"]         = "forgecode"
            alias["vibe kit grok cli"]        = "grok cli"
            alias["qwen code qwen code"]      = "qwen code"
            alias["shareai lab kode"]         = "kode"
            alias["amazon q developer cli"]   = "amazon q"
            alias["llm"]                      = "llm cli"
            alias["aider chat"]               = "aider"
        }
        {
            key = tolower($2)
            sub(/^(npm|pipx|uv): /, "", key)
            gsub(/ *\([^)]*\)/, "", key)
            gsub(/[-_\/@]/, " ", key)
            gsub(/  +/, " ", key); sub(/^ +/, "", key); sub(/ +$/, "", key)
            if (key in alias) key = alias[key]
            k = $1 SUBSEP key
            if (!(k in row)) { row[k] = ++n; cat[n] = $1; fr[n] = $2; id[n] = $3; loc[n] = $4 }
            else { i = row[k]; loc[i] = loc[i] "; " $4 }
        }
        END { for (i = 1; i <= n; i++) print cat[i], fr[i], id[i], loc[i] }
    ')"

    count="$(printf '%s\n' "$sorted" | "$GREP" -c .)"

    # ${(f)...} splits command output on newlines in zsh.
    cats=""
    for c in ${(f)"$(printf '%s\n' "$sorted" | "$CUT" -f1 | "$SORT" -u)"}; do
        case "$c" in
            APP)         kw="ai-app";;
            CLI)         kw="ai-cli";;
            IDE-EXT)     kw="ide-ai-extension";;
            BROWSER-EXT) kw="browser-ai-extension";;
            MCP)         kw="mcp-config";;
            HEURISTIC)   kw="ai-unknown-review";;
            *)           kw="$(lc "$c")";;
        esac
        cats="$cats, $kw"
    done
    cats="${cats#, }"

    findings_body="$(printf '%s\n' "$sorted" | "$SED" 's/\t/ | /g')"
    body="$(printf 'SUMMARY: %s finding(s); categories: %s\n%s' "$count" "$cats" "$findings_body")"
fi

# Write atomically so recon sees either the old complete file or the new one.
"$MKDIR" -p "$STATE_DIR" 2>/dev/null
if (( UID == 0 )); then
    "$CHOWN" root:wheel "$STATE_DIR" 2>/dev/null
fi
"$CHMOD" 0700 "$STATE_DIR" 2>/dev/null   # root-only: the only reader (the EA) is root

tmpfile="$STATE_FILE.tmp.$$"
if ! printf '%s' "$body" > "$tmpfile"; then
    print -u2 "ai-inventory-collector: failed to write temporary state file: $tmpfile"
    exit 1
fi
if (( UID == 0 )); then
    "$CHOWN" root:wheel "$tmpfile" 2>/dev/null
fi
"$CHMOD" 0600 "$tmpfile" 2>/dev/null   # root-only: usernames/paths are mildly sensitive
if ! "$MV" -f "$tmpfile" "$STATE_FILE"; then
    print -u2 "ai-inventory-collector: failed to rename temporary state file into place: $STATE_FILE"
    exit 1
fi

exit 0
__AI_COLLECTOR_EOF__
chown root:wheel "${COLLECTOR_DEST}"
chmod 0755 "${COLLECTOR_DEST}"

log "Creating state directory ${STATE_DIR}"
mkdir -p "${STATE_DIR}"
chown root:wheel "${STATE_DIR}"
chmod 0700 "${STATE_DIR}"

log "Recording interval ${START_INTERVAL}s -> ${STATE_DIR}/interval (EA staleness = 2x)"
printf '%s\n' "${START_INTERVAL}" > "${STATE_DIR}/interval"
chown root:wheel "${STATE_DIR}/interval"
chmod 0644 "${STATE_DIR}/interval"

log "Writing LaunchDaemon ${PLIST_DEST} (Label ${LABEL})"
cat > "${PLIST_DEST}" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>${LABEL}</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/zsh</string>
		<string>--no-rcs</string>
		<string>${COLLECTOR_DEST}</string>
	</array>
	<key>StartInterval</key>
	<integer>${START_INTERVAL}</integer>
	<key>RunAtLoad</key>
	<true/>
	<key>ProcessType</key>
	<string>Background</string>
	<key>StandardOutPath</key>
	<string>${LOG_FILE}</string>
	<key>StandardErrorPath</key>
	<string>${LOG_FILE}</string>
</dict>
</plist>
PLIST_EOF
chown root:wheel "${PLIST_DEST}"
chmod 0644 "${PLIST_DEST}"

log "(Re)loading via modern launchctl subcommands (bootout/enable/bootstrap/kickstart)"
launchctl bootout "system/${LABEL}" 2>/dev/null || true
# Clear a persistent disabled override before bootstrap.
launchctl enable "system/${LABEL}"
launchctl bootstrap system "${PLIST_DEST}"
launchctl kickstart -k "system/${LABEL}"

log "Done. Verify with: launchctl print system/${LABEL}"
log "First state file should appear within a few seconds at ${STATE_DIR}/result.txt"
exit 0
