#!/bin/bash
# SPDX-FileCopyrightText: 2026 Robert Flanagan and macadmin-toolbox contributors
# SPDX-License-Identifier: MIT
#
# Name:        build-installer.sh
# Purpose:     Generate the fully self-contained install.sh from its template
#              (install.sh.in) plus the single-source-of-truth collector
#              (intel-app-auditor.zsh), embedded verbatim via a heredoc.
# Context:     Standalone, run by a maintainer after editing either source:
#              ./build-installer.sh
# Parameters:  none
# Tested on:   macOS 15.4.1 (live, 24E263, arm64) + macOS 15 Sequoia (Tart VM)
# Author:      Robert Flanagan (@r4828)
#
# The generated install.sh needs NOTHING co-located at run time -- deliver it
# as a single Jamf Script payload. Same inputs produce a byte-identical
# install.sh (idempotent).

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/install.sh.in"
COLLECTOR="${SCRIPT_DIR}/intel-app-auditor.zsh"
OUTPUT="${SCRIPT_DIR}/install.sh"
MARKER='#@@EMBEDDED_COLLECTOR@@'
DELIM='__INTEL_AUDITOR_COLLECTOR_EOF__'

[ -f "${TEMPLATE}" ]  || { echo "build-installer.sh: missing template ${TEMPLATE}" >&2; exit 1; }
[ -f "${COLLECTOR}" ] || { echo "build-installer.sh: missing collector ${COLLECTOR}" >&2; exit 1; }

# The heredoc delimiter must be single-quoted (so the collector's $..., $(...)
# and backticks are written literally) AND must not occur anywhere in the
# collector, or the heredoc would terminate early. Abort if it collides.
if grep -qF -- "${DELIM}" "${COLLECTOR}"; then
    echo "build-installer.sh: heredoc delimiter '${DELIM}' occurs in the collector; pick a safer unique delimiter." >&2
    exit 1
fi

if ! grep -qF -- "${MARKER}" "${TEMPLATE}"; then
    echo "build-installer.sh: placeholder '${MARKER}' not found in ${TEMPLATE}" >&2
    exit 1
fi

awk -v marker="${MARKER}" -v delim="${DELIM}" -v collector="${COLLECTOR}" '
NR == 1 {
    print $0
    print "# ============================================================================="
    print "# GENERATED by build-installer.sh from install.sh.in + intel-app-auditor.zsh"
    print "# DO NOT EDIT THIS FILE; edit the sources and re-run ./build-installer.sh"
    print "# ============================================================================="
    next
}
$0 == marker {
    print "cat > \"${COLLECTOR_DEST}\" <<'"'"'" delim "'"'"'"
    while ((getline line < collector) > 0) print line
    close(collector)
    print delim
    next
}
{ print }
' "${TEMPLATE}" > "${OUTPUT}.tmp.$$"

mv -f "${OUTPUT}.tmp.$$" "${OUTPUT}"
chmod 0755 "${OUTPUT}"
echo "build-installer.sh: wrote ${OUTPUT} (collector embedded via heredoc delimiter ${DELIM})"
